try:
    print(x)
except:
    print("An exception occured")
else:
    print("There is no exception")